# Generated by Django 2.1.5 on 2019-01-29 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='sid',
            new_name='age',
        ),
    ]
